name: todo_reminder_app
description: A lightweight todo & reminder Flutter app (scaffold for development).
publish_to: 'none'
version: 0.1.0
environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.4.2
  timezone: ^0.10.1
  hive: ^2.2.3
  flutter_riverpod: ^3.0.1
  speech_to_text: ^7.3.0
  flutter_tts: ^4.2.3
  uuid: ^4.5.1
  hive_flutter: ^1.1.0
  flutter_local_notifications_linux: ^6.0.0
  intl: ^0.20.2
  js: ^0.7.2
  # Firebase packages (required for sync). Uncommented to enable Firestore
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  google_sign_in: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
