name: aireminder
description: AI-powered reminder and todo app with smart scheduling.
publish_to: 'none'
version: 1.0.0+2
environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.4.2
  timezone: ^0.10.1
  hive: ^2.2.3
  flutter_riverpod: ^3.0.1
  speech_to_text: ^7.3.0
  flutter_tts: ^4.2.3
  uuid: ^4.5.1
  hive_flutter: ^1.1.0
  flutter_local_notifications_linux: ^6.0.0
  intl: ^0.20.2
  js: ^0.7.2
  # Firebase packages (required for sync). Uncommented to enable Firestore
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  google_sign_in: ^7.2.0
  google_mobile_ads: ^5.2.0
  # Image processing and AI
  image_picker: ^1.0.4
  http: ^1.1.0
  path_provider: ^2.1.1
  mime: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  image_path: "play_store_assets/icons/app_icon_1024x1024.png"
  min_sdk_android: 21 # Android 5.0
